"""
Report generation — turn an audit log into something a person can read.

A JSONL log is a good record and a poor document. The people who most need to
see it — a compliance reviewer, a security lead, an engineer's manager — are
not going to grep a file. This module turns the log into a summary that
answers the questions they actually ask:

    How many facts were checked, and what happened to them?
    What was blocked, and on what grounds?
    What is sitting in review, waiting on a human?
    Which rules were in force, and did they change mid-period?

Deliberately plain. Text by default, markdown on request. No HTML, no
templates, no charting library — presentation for the web belongs in the
delivery layer, not here. A report that needs a browser to be read is not
much use in an email thread or a ticket.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Optional, Union

from .audit import AuditLog


def _rule(char: str = "-", width: int = 74) -> str:
    return char * width


def _truncate(text: str, limit: int = 60) -> str:
    text = (text or "").replace("\n", " ").strip()
    return text if len(text) <= limit else text[: limit - 1] + "\u2026"


def generate_report(
    log: Union[AuditLog, str, Path, None] = None,
    fmt: str = "text",
    max_examples: int = 10,
    path: Optional[Union[str, Path]] = None,
) -> str:
    """
    Produce a human-readable summary of an audit log.

    Args:
        log           an AuditLog, a path to a .jsonl file, or None for the default
        fmt           "text" or "markdown"
        max_examples  how many blocked / flagged entries to list in full
        path          if given, write the report there as well as returning it

    Returns the report as a string.
    """
    if log is None:
        log = AuditLog()
    elif isinstance(log, (str, Path)):
        log = AuditLog(log)

    entries = log.entries()
    stats = log.summary()

    if fmt == "markdown":
        report = _render_markdown(entries, stats, max_examples)
    else:
        report = _render_text(entries, stats, max_examples)

    if path:
        Path(path).write_text(report, encoding="utf-8")

    return report


# --------------------------------------------------------------------------
# Shared analysis
# --------------------------------------------------------------------------

def _analyse(entries: list[dict]) -> dict:
    blocked = [e for e in entries if e.get("verdict") == "REJECT"]
    flagged = [e for e in entries if e.get("verdict") == "REVIEW"]
    stored = [e for e in entries if e.get("verdict") == "STORE"]

    # Why things were flagged. The reason text is generated by the gate from a
    # small fixed set, so grouping on a prefix is stable enough to be useful
    # and honest about being approximate.
    flag_reasons = Counter()
    for e in flagged:
        reason = e.get("reason", "")
        if "misattribution" in reason.lower():
            flag_reasons["Possible misattribution"] += 1
        elif "unrelated" in reason.lower():
            flag_reasons["Source and fact unrelated"] += 1
        else:
            flag_reasons["Neither supported nor contradicted"] += 1

    timestamps = sorted(e.get("timestamp", "") for e in entries if e.get("timestamp"))

    return {
        "blocked": blocked,
        "flagged": flagged,
        "stored": stored,
        "flag_reasons": flag_reasons,
        "first": timestamps[0] if timestamps else None,
        "last": timestamps[-1] if timestamps else None,
    }


# --------------------------------------------------------------------------
# Text rendering
# --------------------------------------------------------------------------

def _render_text(entries: list[dict], stats: dict, max_examples: int) -> str:
    a = _analyse(entries)
    out: list[str] = []

    out.append(_rule("="))
    out.append("  MEMORY GATE — AUDIT REPORT")
    out.append(_rule("="))
    out.append(f"  log:      {stats['path']}")
    if a["first"]:
        out.append(f"  period:   {a['first']}  to  {a['last']}")
    out.append("")

    if stats["total"] == 0:
        out.append("  No decisions recorded.")
        out.append("")
        return "\n".join(out)

    out.append("  DECISIONS")
    out.append(_rule())
    out.append(f"  Facts checked           {stats['total']:>6}")
    out.append(f"  Stored                  {stats['stored']:>6}   {stats['store_rate']:>5.1f}%")
    out.append(f"  Blocked                 {stats['rejected']:>6}   {stats['reject_rate']:>5.1f}%")
    out.append(f"  Flagged for review      {stats['flagged_for_review']:>6}   {stats['review_rate']:>5.1f}%")
    out.append("")

    if a["flag_reasons"]:
        out.append("  WHY FACTS WERE FLAGGED")
        out.append(_rule())
        for reason, count in a["flag_reasons"].most_common():
            out.append(f"  {count:>4}   {reason}")
        out.append("")

    if a["blocked"]:
        out.append(f"  BLOCKED — contradicted their source  (showing {min(len(a['blocked']), max_examples)} of {len(a['blocked'])})")
        out.append(_rule())
        for e in a["blocked"][:max_examples]:
            out.append(f"  fact:    {_truncate(e.get('fact', ''))}")
            out.append(f"  source:  {_truncate(e.get('source', ''))}")
            contra = e.get("contradiction")
            if contra is not None:
                out.append(f"  evidence: contradiction {contra:.3f}")
            out.append("")

    if a["flagged"]:
        out.append(f"  AWAITING REVIEW  (showing {min(len(a['flagged']), max_examples)} of {len(a['flagged'])})")
        out.append(_rule())
        for e in a["flagged"][:max_examples]:
            out.append(f"  fact:    {_truncate(e.get('fact', ''))}")
            out.append(f"  source:  {_truncate(e.get('source', ''))}")
            out.append(f"  reason:  {_truncate(e.get('reason', ''), 90)}")
            out.append("")

    out.append("  POLICIES IN FORCE")
    out.append(_rule())
    policies = stats.get("policies", {})
    if len(policies) > 1:
        out.append("  More than one policy appears in this log. Rates above combine")
        out.append("  periods governed by different rules; the breakdown below separates them.")
        out.append("")
    for fingerprint, info in policies.items():
        verdicts = ", ".join(f"{k} {v}" for k, v in sorted(info["verdicts"].items()))
        out.append(f"  {info['name']} v{info['version']}  [{fingerprint}]")
        out.append(f"      {info['count']} decisions   ({verdicts})")
    out.append("")

    out.append(_rule("="))
    out.append("  Every decision above is recorded in full in the audit log,")
    out.append("  including the model's raw scores and the policy that produced it.")
    out.append(_rule("="))
    out.append("")

    return "\n".join(out)


# --------------------------------------------------------------------------
# Markdown rendering
# --------------------------------------------------------------------------

def _render_markdown(entries: list[dict], stats: dict, max_examples: int) -> str:
    a = _analyse(entries)
    out: list[str] = []

    out.append("# Memory Gate — Audit Report")
    out.append("")
    out.append(f"**Log:** `{stats['path']}`  ")
    if a["first"]:
        out.append(f"**Period:** {a['first']} to {a['last']}")
    out.append("")

    if stats["total"] == 0:
        out.append("No decisions recorded.")
        return "\n".join(out)

    out.append("## Decisions")
    out.append("")
    out.append("| Outcome | Count | Share |")
    out.append("|---|---:|---:|")
    out.append(f"| Facts checked | {stats['total']} | |")
    out.append(f"| Stored | {stats['stored']} | {stats['store_rate']}% |")
    out.append(f"| Blocked | {stats['rejected']} | {stats['reject_rate']}% |")
    out.append(f"| Flagged for review | {stats['flagged_for_review']} | {stats['review_rate']}% |")
    out.append("")

    if a["flag_reasons"]:
        out.append("## Why facts were flagged")
        out.append("")
        out.append("| Reason | Count |")
        out.append("|---|---:|")
        for reason, count in a["flag_reasons"].most_common():
            out.append(f"| {reason} | {count} |")
        out.append("")

    if a["blocked"]:
        out.append(f"## Blocked — contradicted their source ({len(a['blocked'])})")
        out.append("")
        out.append("| Fact | Source | Contradiction |")
        out.append("|---|---|---:|")
        for e in a["blocked"][:max_examples]:
            contra = e.get("contradiction")
            contra_str = f"{contra:.3f}" if contra is not None else ""
            out.append(
                f"| {_truncate(e.get('fact', ''))} | {_truncate(e.get('source', ''))} | {contra_str} |"
            )
        out.append("")

    if a["flagged"]:
        out.append(f"## Awaiting review ({len(a['flagged'])})")
        out.append("")
        out.append("| Fact | Source | Reason |")
        out.append("|---|---|---|")
        for e in a["flagged"][:max_examples]:
            out.append(
                f"| {_truncate(e.get('fact', ''))} | {_truncate(e.get('source', ''))} "
                f"| {_truncate(e.get('reason', ''), 90)} |"
            )
        out.append("")

    out.append("## Policies in force")
    out.append("")
    policies = stats.get("policies", {})
    if len(policies) > 1:
        out.append(
            "> More than one policy appears in this log. The rates above combine "
            "periods governed by different rules; the breakdown below separates them."
        )
        out.append("")
    out.append("| Policy | Version | Fingerprint | Decisions |")
    out.append("|---|---|---|---:|")
    for fingerprint, info in policies.items():
        out.append(
            f"| {info['name']} | {info['version']} | `{fingerprint}` | {info['count']} |"
        )
    out.append("")
    out.append(
        "*Every decision is recorded in full in the audit log, including the "
        "model's raw scores and the policy that produced it.*"
    )
    out.append("")

    return "\n".join(out)